### ISSUE TITLE
[<- assigns to wrong indices on omitted commas

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/magclass#150] opened 2023-06-09 12:15 UTC
This originates from #149.  Over lunch I figured out what the actual bug is in pik-piam/mrremind#403.

Consider two `magpie` objects, `foo` and `bar`, with identical dimensions, but differing index order in the spatial dimension:
```
> foo <- new.magpie(c('A', 'B', 'C'), 1:3)
> 
> bar <- foo
> bar[,,] <- rep((1:3) * 1000, 3) + rep(1:3, each = 3)
> bar <- bar[c('A', 'C', 'B'),,]
> bar
An object of class "magpie"
, , 1

      year
region y0001 y0002 y0003
     A  1001  1002  1003
     C  3001  3002  3003
     B  2001  2002  2003
>
> getRegions(foo)
[1] "A" "B" "C"
> getRegions(bar)
[1] "A" "C" "B"
```

If `bar` is assigned to `foo` with "fully qualified" (empty) `[<-` parameters, the result is as expected.
```
> foo[,,] <- bar
> foo
An object of class "magpie"
, , 1

      year
region y0001 y0002 y0003
     A  1001  1002  1003
     B  2001  2002  2003
     C  3001  3002  3003
```

If `bar` is assigned to `foo` with omitted (empty) `[<-` parameters, however, the result is wrong:
```
> foo <- new.magpie(c('A', 'B', 'C'), 1:3)
> foo[,] <- bar
> foo
An object of class "magpie"
, , 1

      year
region y0001 y0002 y0003
     A  1001  1002  1003
     B  3001  3002  3003
     C  2001  2002  2003```
```
No warning, no indication, just plain wrong data.

We could have dozens such assignments in the code base.

**Comment by tscheypidi** [comment] 2023-06-14 07:58
Hi @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q,

this is a problem where I have now idea how to fix it. The problem is that there are two cases which I cannot distinguish from within the function. The first case is the one you are describing, where the second comma is missing:

```
foo[,] <- bar
```

The other one is the case where the object should be adressed in its vectorized form:

```
foo[] <- bar
```

In both cases this looks inside the function like this:

```
Browse[1]> i
Error in .local(x, i, j, ..., value) : 
  argument "i" is missing, with no default
Browse[1]> j
Error in .local(x, i, j, ..., value) : 
  argument "j" is missing, with no default
Browse[1]> k
      year
region y0001 y0002 y0003
     A  1001  1002  1003
     C  3001  3002  3003
     B  2001  2002  2003
Browse[1]> value
Error: argument "value" is missing, with no default
```

Hence, if I introduce a warning here this warning would also show up in a lot of valid cases or if I would change the behavior of the function it would destroy a lot of functioning workflows. 

Do you perhaps have an idea how to fix it? If not I suggest to close this issue as well as #149

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment] 2023-06-14 12:10
Is there a legitimate use case for `foo[]`?
As I see it, it is sufficient to distinguish between "fully qualified" (but possibly empty) coordinates (`foo[,,]`) and everything else (both `foo[,]` and `foo[]`), which would be deemed suspect and trigger a warning at minimum.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment] 2023-06-14 13:17
> In some cases you just need to address an array in its vectorized form.

I'm not convinced that is the case.  There appear to be 68 instances of `[] <-` in the code base
```
$ find /p/projects/rd3mod/github/ -name "*.R" | xargs grep "^[^#]*\[\] *<-" | tr -d '\r' | awk -F "<-" '{ sub(/^ */, "", $NF); sub(/ *$/, "", $NF); a[$NF]++ } END { PROCINFO["sorted_in"] = "@val_num_desc"; for (i in a) printf("%2d: %s\n", a[i], i) }' 
21: 0
16: NA
 6: 1
 4: abs(round(isoproductionMAG - toolIso2CellCountries(productionFAO), 4)) > 0
 3: area
 1: rep(grid[translateGrid2Mag], length(years))
 1: 1:2
 1: x["FJI.57129", , ]
 1: x["ARG.33456", , ]
 1: (isoPastureYields == 0) * isoMismatch * (1 - noPastureArea)
 1: 1.
 1: (isoPastureArea == 0) * isoMismatch
 1: calcOutput("IPCCfracLeach", aggregate = FALSE, cellular = TRUE)
 1: newFunctionCoeff
 1: abs(diff)
 1: (isoMAGCroparea == 0) * isoMismatch
 1: length(legend_breaks)+1
 1: data
 1: as.double(x[])
 1: (isoMAGYields == 0) * isoMismatch * (1 - noMAGCroparea)
 1: x[as.array((ncells * nyears) * (rep(1:ndata, each = ncells) - 1)
 1: length(legend_breaks) + 1
 1: TRUE
```
only 21 of which are not definitely a scalar 
```
 4: abs(round(isoproductionMAG - toolIso2CellCountries(productionFAO), 4)) > 0
 3: area
 1: rep(grid[translateGrid2Mag], length(years))
 1: 1:2
 1: x["FJI.57129", , ]
 1: x["ARG.33456", , ]
 1: (isoPastureYields == 0) * isoMismatch * (1 - noPastureArea)
 1: (isoPastureArea == 0) * isoMismatch
 1: calcOutput("IPCCfracLeach", aggregate = FALSE, cellular = TRUE)
 1: newFunctionCoeff
 1: abs(diff)
 1: (isoMAGCroparea == 0) * isoMismatch
 1: data
 1: as.double(x[])
 1: (isoMAGYields == 0) * isoMismatch * (1 - noMAGCroparea)
 1: x[as.array((ncells * nyears) * (rep(1:ndata, each = ncells) - 1)
```
I have not looked into them specifically, but I am fairly certain that
1. some of them can be converted from `[] <-` to `[,,] <-` without further modification
2. all of them can be converted from `[] <-` to `[,,] <-` with explicitly stating along which axes elements should be repeated
3. most of them would benefit of stating that explicitly, in terms of intelligibility and robustness

> This is also done sometimes by external functions applied on a magpie object.

Well, it's not like the `magclass` interface was immutable in the past.  And those external functions are susceptible to these kinds of errors, too.

> So nothing we could just not allow for without breaking a lot of things

A warning would allow us to track this behaviour through our own code without breaking anything.  One could also implement an option along the lines of `_R_CHECK_LENGTH_1_LOGIC2_` to either do nothing, or issue a warning or an error, giving the user a choice in the matter.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment] 2023-06-14 13:32
Which array function relies on `[] <-`?

**Comment by tscheypidi** [comment] 2023-06-15 07:12
I don't remember anymore which particular functions that are. If you are curious, you can try it out by building your own magclass version which does not support it anymore and see what breaks.

I will close this issue now as it does not seem to lead anywhere. Feel free to reopen it if you plan to further investigate and work on it.

**Closed by tscheypidi** 2023-06-15 07:12 UTC
Labels: bug
